### ISSUE TITLE
[Suggestion] Mega Cells.

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica10#244] opened 2024-11-29 04:54 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/mega-cells/files/5920216

### Why would you like the mod added?

Provides larger storage options for Applied Energistics.

**Comment by NielsPilgaard** [comment] 2024-12-01 18:29
No thanks, nearly duplicate of #62 and #181 😅

**Closed by NielsPilgaard** 2024-12-01 18:29 UTC
Labels: Suggestion
