### ISSUE TITLE
EMI not adding items that share components

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#16] opened 2024-07-02 07:08 UTC
### Modpack Version

1.2.0

### Describe your issue.

If a recipe can use different types of the same block, for example stones, when you try to add the items from your inventory with the plus button it will not add those blocks. inthe example below, if I have regular stone in my inventory it will add all the other items but not the stone.

![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/05f8e61b-7b42-42f0-bd57-b3ddc21fc0c0)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jordacus

**Comment by SupaJordy** [comment] 2024-07-02 07:09
Strangely, it did add the mercury though.

**Comment by NielsPilgaard** [comment] 2024-07-02 17:50
Thanks for the report. Please update to E10 1.3.0 and see if it persists :)

**Comment by NielsPilgaard** [comment] 2024-07-03 19:19
I can't reproduce this in 1.2.0 even, closing 👍

**Closed by NielsPilgaard** 2024-07-03 19:19 UTC
Labels: bug, fixed in next release

**Comment by SupaJordy** [comment] 2024-07-04 15:27
Can confirm it works in 1.3.0. Sorry, it took a while due to issues I was having with 1.3.0.
