### ISSUE TITLE
Occultism recipes not showing for many rituals 

### ISSUE THREAD

**Issue by calog3no** [EnigmaticaModpacks/Enigmatica10#90] opened 2024-08-19 14:19 UTC
### Modpack Version

1.9

### Describe your issue.

Many of the rituals in occultism are not showing in the occultism book or EMI.
![2024-08-19_10 08 12](https://github.com/user-attachments/assets/a95ab4ef-cde1-43c3-aa59-f29ed0d48452)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

calog3no

**Comment by NielsPilgaard** [comment] 2024-08-19 15:04
I expect that this is because we're not on the latest jei/Occultism versions, because the latest jei is marked as 1.21.1 only.
@klikli-dev is that a reasonable assumption?

**Comment by theboo** [comment] 2024-08-19 15:17
Occultism *should* have native EMI support now so jei *should* be irrelevant as far as function, but since it also works with jei, and we need jei under emi for other mods it has to match with the version occultism is asking for(even tho marked optional)... Curious if this issue has something to do with the emi compat vs jei version 

I don't quite understand how the "version range" in the new neo mods.toml works tho...

<https://github.com/klikli-dev/occultism/blob/5900e7bfa315925cec068469653e42f86132a564/src/main/resources/META-INF/neoforge.mods.toml#L87>

**Comment by theboo** [comment] 2024-08-19 15:19
Just realized you meant it might be fixed in latest occultism which we can't use because of the available jei versions on 1.21... ignore me lol

**Comment by klikli-dev** [comment] 2024-08-20 08:07
Mea culpa - I will release a version today that accepts older JEI. I missed that JEI restricted its latest versions to 1.21.1

**Comment by NielsPilgaard** [comment] 2024-08-20 19:46
Alright I've updated to the latest version of Modonomicon and Occultism, and the issue remains:
![image](https://github.com/user-attachments/assets/0ac4dae0-620f-4fe9-940e-bb14e7e0af60)

**Comment by klikli-dev** [comment] 2024-08-21 09:08
Hmm I will have to try with E10, in my local install I see the recipes

**Comment by klikli-dev** [comment] 2024-08-21 09:38
@NielsPilgaard it looks like the recipes are not loaded (neither modonomicon nor jei find them). 
In an occultism only instance, and in ATM10 with .. a lot of stuff (but no occultism ritual recipe modification that I am aware of, besides replacing the multiblocks for the pentacles in modonomicon) this does not happen.

Is it possible that e.g. your kubejs script has an issue causing recipes not to be re-added after modification? 
Kube hat a lot of changes in 1.21(.1) so maybe something is missing?

**Comment by NielsPilgaard** [comment] 2024-08-21 10:09
@MuteTiefling please see above, what do you think?

**Comment by MuteTiefling** [comment] 2024-08-21 13:49
Certainly possible. I don't have easy access to a pc for testing, however.

**Comment by NielsPilgaard** [comment] 2024-08-21 17:03
Alright, I'll give it a go if I can find time for it 👍

**Comment by MuteTiefling** [comment] 2024-08-21 17:12
If not, I'll be able to in a couple days

**Comment by MuteTiefling** [comment] 2024-08-24 16:09
Testing with everything updated to 1.21.1.

With our kubejs scripts as they exist in release, the issue persists.
Without our occultism specific scripts, the issue persists.
Without any kubejs scripts, the issue is resolved.

**Comment by MuteTiefling** [comment] 2024-08-24 16:25
More specifically, I need to remove all recipe scripts for the issue to go away. The non recipe scripts are having no impact.

**Comment by klikli-dev** [comment] 2024-08-29 13:29
@MuteTiefling is OccultismKubeJS present? 
I am not sure if it actually does anything in your use case, but according to the KubeJS Authors, the recipe definitions contained in the addon give Kube some addtional info that prevents it from running some code that was problematic e.g. with tags (basically it tries to get recipe information by analyzing the recipe result), which may also cause issues here

**Comment by MuteTiefling** [comment] 2024-08-29 13:45
@klikli-dev We do have occultism kubejs, yes 

We're also updated to 1.21.1 now and I'm still seeing the issue.

**Comment by MuteTiefling** [comment] 2024-08-29 14:57
What gets me is the seemingly random nature of affected recipes. It's very specific ones that don't show, but I don't see any correlation. Most of them are possession recipes. But then the silverfish horde and endermite recipes are fine.

**Comment by MuteTiefling** [comment] 2024-08-29 15:04
Although, those two do have an `item_to_use` and the rest do not. Looking through the book, every single recipe in the possession chapter is broken aside from the two that use this.

**Comment by klikli-dev** [comment] 2024-08-29 15:05
@MuteTiefling can you point me to where / how you modify the recipes?
Maybe I can re-create that locally and deploy a fix via the kubejs addon

**Comment by MuteTiefling** [comment] 2024-08-29 15:07
@klikli-dev our occultism specific recipes are here https://github.com/EnigmaticaModpacks/Enigmatica10/tree/master/kubejs/server_scripts/recipes/occultism

But, removing them does not resolve the issue. I have to remove every single recipe altering script for your recipes to re-appear. Even if those scripts are unrelated to Occultism.

**Comment by klikli-dev** [comment] 2024-08-29 16:28
ok it reproduces if I put just your recipe script into my kubejs addon workspace. Maybe I can find out more!

**Comment by klikli-dev** [comment] 2024-08-29 16:58
I posted about the issue in the kubejs discord and asked them to give me directions on how to further diagnose this!

**Comment by pietro-lopes** [comment] 2024-08-29 20:12
I tested in a clean instance (Kubejs and Occulstim only) and this worked for me.

```js
ServerEvents.recipes((event) => {
    event.forEachRecipe({ type: 'occultism:ritual' }, (r) => {
        let recipe = r.json.asMap();
        let recipe_id = r.getId();
        if (recipe.spirit_max_age) {
            if (recipe_id.includes('_trader')) {
                // Remove decay from Traders
                delete recipe.spirit_max_age;
            } else {
                // Reduce delay for all other spirits (weather/daytime rituals)
                recipe.spirit_max_age = 10;
            }
        }

        // Override default craft time for all recipes
        recipe.duration = 20;
    });
});
```

**Comment by MuteTiefling** [comment] 2024-09-01 19:18
Found the common trace here:

Tried re-adding the recipe myself as an interim solution and it doesn't like  `Invalid component 'entity_to_sacrifice' ({tag: entity_type_tag, display_name: string}) `
```
[15:14:22] [ERROR] ! server_scripts:recipes/occultism/ritual.js#58: Failed to create custom recipe from json {"activation_item":{"item":"occultism:book_of_binding_bound_afrit"},"duration":20,"entity_to_sacrifice":{"display_name":"ritual.occultism.sacrifice.fish","tag":"c:fish"},"entity_to_summon":"occultism:possessed_elder_guardian","ingredients":[{"item":"minecraft:oxidized_copper"},{"item":"minecraft:prismarine"},{"item":"minecraft:prismarine_bricks"},{"item":"minecraft:dark_prismarine"},{"item":"minecraft:wet_sponge"},{"item":"minecraft:sea_lantern"},{"item":"minecraft:water_bucket"},{"item":"minecraft:water_bucket"},{"item":"minecraft:water_bucket"},{"tag":"c:gems/emerald"}],"pentacle_id":"occultism:possess_afrit","result":{"components":{"minecraft:item_name":"{\"translate\":\"item.occultism.ritual_dummy.possess_elder_guardian\"}","minecraft:lore":["{\"translate\":\"item.occultism.ritual_dummy.possess_elder_guardian.tooltip\"}"]},"count":1,"id":"minecraft:heart_of_the_sea"},"ritual_dummy":{"count":1,"id":"occultism:ritual_dummy/possess_elder_guardian"},"ritual_type":"occultism:summon","id":"occultism:ritual/possess_elder_guardian","type":"occultism:ritual"}: Invalid component 'entity_to_sacrifice' ({tag: entity_type_tag, display_name: string}) - java.lang.ClassCastException: class com.mojang.serialization.DataResult$Success cannot be cast to class java.lang.String (com.mojang.serialization.DataResult$Success is in module datafixerupper@8.0.16 of loader 'MC-BOOTSTRAP' @63440df3; java.lang.String is in module java.base of loader 'bootstrap')
```

**Comment by MuteTiefling** [comment] 2024-09-01 19:31
And if I remove that value, the recipe loads without issue.

**Comment by klikli-dev** [comment] 2024-09-02 09:33
That is a great find, although I am not sure why it happens, as the KubeJS people helped me set up that part. I will investigate, maybe it is outdated or we overlooked something

**Comment by MuteTiefling** [comment] 2024-09-03 13:03
Awesome! I'll pop it in my test instance as soon as I can, thanks for your efforts!

**Comment by MuteTiefling** [comment] 2024-09-04 05:20
Woot! Working great! Thanks for the fix @klikli-dev, you're the best :D

**Comment by klikli-dev** [comment] 2024-09-04 07:05
Thanks a lot for your help in this, this would sooner or later trip up a lot of mod pack devs and you did the legwork in tracing it down. 
Kube now also knows about the specifics of the issue and maybe they can fix things on their end too, but for mod devs the option I took is always a possibility: replace recipe component builders (or their equivalent json snippets in the json schemata) with explicit code-defined components.

**Closed** 2024-09-07 18:32 UTC
Labels: bug, fixed in next release
