### ISSUE TITLE
Occultism pentacle recipes not showing

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#9] opened 2024-06-26 11:00 UTC
### Modpack Version

1.2.0

### Describe your issue.

Recipes that are made using Occultism pentacles are not showing in EMI and are blank in the Occultism book.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jordacus

**Comment by SupaJordy** [comment] 2024-06-26 16:33
If it helps, someone has advised:

There is an update for Occultism, but it will not run on the current version of neoforge and the new version of neoforge breaks other mods.  It will likely get sorted out over time, but we need to wait for Occultism.

**Comment by NielsPilgaard** [comment] 2024-06-26 17:03
@klikli-dev got another one for you :D

**Comment by klikli-dev** [comment] 2024-06-26 18:00
Thanks! I'll take a look, I think this one is not yet fixed in latest occultism

**Comment by klikli-dev** [comment] 2024-06-26 18:23
@SupaJordy could you possibly provide screenshots of the issue? To me the recipes render both in JEI and in the occultism book (testing EMI is a bit tricky right now in the dev environment but as it uses the same code as JEI I *presume* it should work there too) 

Maybe I am misunderstanding what is not working

**Comment by MuteTiefling** [comment] 2024-06-26 18:45
There's nothing to screenshot, unfortunately. Checking Emi for the recipe finds nothing.

It's like the entire recipe tab is missing

**Comment by MommyHeather** [comment] 2024-06-26 19:03
![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/66441550/73b0bfdc-4668-4147-b604-be9ddbcf1a5a)
Okay, hitting R on the soul gem in EMI just does *nothing* at all.

This however does NOT happen in an instance that has JEI only.
![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/66441550/99e1ece0-29cf-45db-b8fc-ad6eb012ef5c)

**Comment by SupaJordy** [comment] 2024-06-26 20:25
Additionally, this is what the book looks like for pentacle recipes:

![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/343fb7fc-73cd-430f-81d8-326e4f260fa6)
![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/c57a6582-4fd9-4cf4-bf1b-76c2fd89c518)
![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/40a1c247-dc08-4ca2-bde8-50aeb419ebd8)

**Comment by klikli-dev** [comment] 2024-06-27 03:17
Thanks! That is very helpful so I can try to reproduce it!

**Comment by klikli-dev** [comment] 2024-06-27 04:30
Thanks everyone - I pushed a fix, please test with release/v1.21-1.134.2 as soon as you can cross over into the post-breaking-changes neo versions. 

EMI should be fixed, and the book worked for me without changes. If any issues remain after 1.134.2 let me know so we can get them fixed up too!

**Comment by MuteTiefling** [comment] 2024-07-01 14:21
So, I had thought this was fixed in-dev, but I've noticed one small lingering related issue.

If I check Uses for Raw Iron, I can find the Foliot Crusher recipe.
I see the recipe in the Dictionary of Spirits
However, if I try to pull up recipes for the Ritual Dummy item, nothing shows. 
This seems to be the case for any of the ritual dummies.

**Closed** 2024-07-01 18:26 UTC
Labels: bug, fixed in next release
