### ISSUE TITLE
ExtendedAE

### ISSUE THREAD

**Issue by flece** [EnigmaticaModpacks/Enigmatica10#181] opened 2024-10-21 16:37 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider

### Why would you like the mod added?

this is a QoL Mod fitting perfect into a kitchensink pack
for me it solves 2 things i dont like about AE2

* more space for Pattern in one Pattern Provider (36 instead of 9)
* reduce Cablemess in my Base without making it to simple
  only found docu in source (https://github.com/GlodBlock/ExtendedAE/blob/1.21.1-neoforge/src/main/resources/assets/extendedae/ae2guide/epp_intro/wireless_connector.md)

tbh: there is also infinity Cells (cobble and water) i dont know if we like that and maybe it can disabled. it can for sure be extendet
https://github.com/GlodBlock/ExtendedAE/wiki/Custom-Infinity-Cell

**Comment by theboo** [comment] 2024-10-21 16:40
Duplicate of:
https://github.com/EnigmaticaModpacks/Enigmatica10/issues/62

Maybe that issue could be reopened for further discussion

**Comment by MuteTiefling** [comment] 2024-10-21 17:10
Closing as duplicate. Further discussion is best kept in one spot as Boo has pointed out.

**Closed by MuteTiefling** 2024-10-21 17:10 UTC
Labels: duplicate, Suggestion
